// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "UK English Only.", Scope = "member", Target = "~M:DestinyItemTagger.Program.CheckForPerk(System.String,System.String[],System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "UK English Only.", Scope = "member", Target = "~M:DestinyItemTagger.Program.CheckForRecomendedPerks(System.String,System.String[]@,System.String[][])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "UK English Only.", Scope = "member", Target = "~M:DestinyItemTagger.Program.CheckForPerkSets(System.String,System.String[]@,System.String[][])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "No copywrite", Scope = "namespace", Target = "~N:DestinyItemTagger")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Comparison only", Scope = "member", Target = "~M:DestinyItemTagger.Main.BtnGo_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "UK English Only.", Scope = "member", Target = "~M:DestinyItemTagger.Main.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "UK English Only.", Scope = "member", Target = "~M:DestinyItemTagger.Main.BtnExport_Click(System.Object,System.EventArgs)")]